# Generated by Django 5.1.4 on 2024-12-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_user_profile_picture_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
